# Generated by Django 4.2.30 on 2026-06-23 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0006_remove_subscription_user_name_chathistory_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='free_messages_sent',
            field=models.IntegerField(default=0),
        ),
    ]
