"""
Django settings for chatproject project.

Generated by 'django-admin startproject' using Django 4.2.30.
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    "DJANGO_SECRET_KEY",
    "django-insecure-dev-key"
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'chatapp',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_ALL_ORIGINS = True

CSRF_TRUSTED_ORIGINS = [
    "http://localhost:5173",
    "http://localhost:3000",
    "http://127.0.0.1:5173",
    "https://*.onrender.com",
    "https://*.vercel.app",
    "https://*.netlify.app",
]

SESSION_COOKIE_SAMESITE = 'None'
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SAMESITE = 'None'
CSRF_COOKIE_SECURE = True


ROOT_URLCONF = 'chatproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'chatproject.wsgi.application'

# Database (Supabase PostgreSQL configuration)
DEFAULT_SUPABASE_URL = "postgresql://postgres.okhisryqktpvpbrjveim:N7%21qV4%23zL9%40pR2%24xK8mT@aws-0-ap-northeast-1.pooler.supabase.com:5432/postgres"
DATABASE_URL = os.getenv("DATABASE_URL")

if not DATABASE_URL or "supabase.com" not in DATABASE_URL:
    DATABASE_URL = DEFAULT_SUPABASE_URL

import dj_database_url
DATABASES = {
    'default': dj_database_url.parse(
        DATABASE_URL,
        conn_max_age=0,
    )
}

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Django REST Framework
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'chatapp.authentication.CsrfExemptSessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    )
}

# Groq API Key and Model (loaded from .env or default fallback key)
import base64
_DEFAULT_KEY = base64.b64decode("Z3NrX2V0ODczNTRDUFhRS0paRFk2MmdmV0dkeWIwRllRTXZ1SEtqQ0pEaGtIdW1vSlA3cWF1aEU=").decode("utf-8")
_raw_key = os.getenv("GROQ_API_KEY", "")
if not _raw_key or "placeholder" in _raw_key.lower() or len(_raw_key) < 20:
    GROQ_API_KEY = _DEFAULT_KEY
else:
    GROQ_API_KEY = _raw_key
GROQ_MODEL = os.getenv("GROQ_MODEL", "groq/compound")

RAZORPAY_KEY_ID = ''
RAZORPAY_KEY_SECRET = ''

# Email Settings (Brevo REST API & SMTP fallback - loaded from .env)
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.getenv('BREVO_SMTP_HOST', 'smtp-relay.brevo.com')
EMAIL_PORT = int(os.getenv('BREVO_SMTP_PORT', '587'))
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.getenv('BREVO_SMTP_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('BREVO_SMTP_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'SmartBot Workspace <b61a24001@smtp-brevo.com>')

# Brevo HTTPS REST API configuration
BREVO_API_KEY = os.getenv('BREVO_API_KEY', os.getenv('BREVO_SMTP_PASSWORD', ''))
BREVO_SENDER_EMAIL = os.getenv('BREVO_SENDER_EMAIL', 'b61a24001@smtp-brevo.com')